# Generated by Django 5.0.6 on 2024-06-30 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_user_group_user_user_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='default_group_id',
            field=models.IntegerField(null=True),
        ),
    ]
