# Generated by Django 5.0.6 on 2024-07-07 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_usersetting_default_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_setting',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.usersetting'),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='default_group_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
