version: '3.10'

services:
  web:
    build: .  # Build from the Dockerfile in the current directory
    command: python3 manage.py runserver 0.0.0.0:8000  # Bind Django to all interfaces
    volumes:
      - ./:/usr/src/app/  # Mount the current directory to /usr/src/app in the container
    ports:
      - "8000:8000"  # Map port 8000 on the host to port 8000 on the container
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db  # Wait for the db service to be ready

  db:
    image: postgres:latest  # Use the latest PostgreSQL image
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"  # Map port 5432 on the host to port 5432 on the container
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]  # Check if PostgreSQL is ready
      interval: 10s
      timeout: 5s
      retries: 5

# Uncomment and configure pgadmin service if needed
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - ./data/pgadmin/:/var/lib/pgadmin
