# Generated by Django 5.0.6 on 2024-05-29 16:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "task_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("task_name", models.CharField(max_length=255)),
                ("task_desc", models.TextField()),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("target_date", models.DateTimeField()),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("urgent", "Urgent"),
                            ("normal", "Normal"),
                            ("low", "Low"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "task_category",
                    models.CharField(
                        choices=[
                            ("grocery", "Grocery"),
                            ("travel", "Travel"),
                            ("leisure", "Leisure"),
                            ("work", "Work"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaskContainer",
            fields=[
                (
                    "container_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("container_name", models.CharField(max_length=255)),
                (
                    "tasks",
                    models.ManyToManyField(related_name="containers", to="task.task"),
                ),
            ],
        ),
    ]
