# Generated by Django 5.0.6 on 2024-05-27 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TaskContainer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("container_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_name", models.CharField(max_length=255)),
                ("task_desc", models.TextField()),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("target_date", models.DateTimeField()),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("urgent", "Urgent"),
                            ("normal", "Normal"),
                            ("low", "Low"),
                        ],
                        default="normal",
                        max_length=10,
                    ),
                ),
                (
                    "task_category",
                    models.CharField(
                        choices=[
                            ("grocery", "Grocery"),
                            ("travel", "Travel"),
                            ("leisure", "Leisure"),
                            ("work", "Work"),
                        ],
                        default="work",
                        max_length=10,
                    ),
                ),
                (
                    "container",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="task.taskcontainer",
                    ),
                ),
            ],
        ),
    ]
