# Generated by Django 5.0.6 on 2024-05-27 11:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="container",
        ),
        migrations.RemoveField(
            model_name="task",
            name="id",
        ),
        migrations.RemoveField(
            model_name="taskcontainer",
            name="id",
        ),
        migrations.AddField(
            model_name="task",
            name="task_id",
            field=models.UUIDField(
                default=uuid.UUID("f6545805-6b0e-4458-9943-ce4b440dadc3"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AddField(
            model_name="taskcontainer",
            name="container_id",
            field=models.UUIDField(
                default=uuid.UUID("039af3a7-0fe4-416e-bbaf-cf6345590137"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AddField(
            model_name="taskcontainer",
            name="tasks",
            field=models.ManyToManyField(related_name="containers", to="task.task"),
        ),
    ]
