# Generated by Django 5.0.6 on 2024-05-27 12:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0002_remove_task_container_remove_task_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="task_category",
            field=models.CharField(
                choices=[
                    ("grocery", "Grocery"),
                    ("travel", "Travel"),
                    ("leisure", "Leisure"),
                    ("work", "Work"),
                ],
                default="grocery",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="task_id",
            field=models.UUIDField(
                default=uuid.UUID("ebdfd9ce-c008-4b08-8fc8-8474f5149b0c"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="taskcontainer",
            name="container_id",
            field=models.UUIDField(
                default=uuid.UUID("0c7bc8e1-001f-4511-8765-000d35456b3f"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
