# Generated by Django 5.0.6 on 2024-07-07 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_remove_taskcontainer_users_task_is_important_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_desc',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
